[[redirects]]
  from = "/2016/02/19/direct-link-to-image-in-google-photos-for-html-image-tag"
  to = "/guides/direct-link-for-posting-google-photos-image/"

[[redirects]]
  from = "/posts/2016-02-19-direct-link-to-image-in-google-photos-for-html-image-tag"
  to = "/guides/direct-link-for-posting-google-photos-image/"

[[redirects]]
  from = "/blog/1-50-if-one-does-not-already-exist"
  to = "/docs-tips/50-01-if-one-does-not-already-exist"

[[redirects]]
  from = "/blog/50-1-if-one-does-not-already-exist"
  to = "/docs-tips/50-01-if-one-does-not-already-exist"
 
[[redirects]]
  from = "/blog/50-50-tip-your-server"
  to = "/docs-tips/50-50-tip-your-server"
  
[[redirects]]
  from = "/:year/:month/:day/:slug"
  to = "/blog/:year-:month-:day-:slug"
  status = 301
  force = false

[[redirects]]
  from = "/posts/:year-:month-:day-:slug"
  to = "/blog/:year-:month-:day-:slug"
  status = 301
  force = false

[[redirects]]
  from = "/posts/*"
  to = "/blog/*"
  status = 301
  force = false

[[redirects]]
  from = "/about/"
  to = "/"